---
title: "Titanic"
author: "Abby Bergman"
date: "11/6/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(modelr)
library(broom)
library(partykit)
library(caret)
library(rsample)
```

```{r, include = FALSE}
#load data
library(titanic)

#open titanic train data set
titanic_train
```

```{r}
#Estimate three different logistic regression models with Survived as the response variable. You may use any combination of the predictors to estimate these models. Don’t just reuse the models from the notes.

#survival by fare
survive_fare <- glm(Survived ~ Fare, data = titanic_train, family = binomial)
summary(survive_fare)

#survival by class
survive_class <- glm(Survived ~ Pclass, data = titanic_train, family = binomial)
summary(survive_class)

#survival by sex
survive_sex <- glm(Survived ~ Sex, data = titanic_train, family = binomial)
summary(survive_sex)
```

```{r}
#Calculate the leave-one-out-cross-validation error rate for each model. Which model performs the best?
#survive_fare

#begin cross validation
loocv_data <- loo_cv(titanic_train)
loocv_data
#

holdout_results <- function(splits){

  mod <- glm(Survived ~ Fare, data = analysis(splits)
             )  
  holdout <- assessment(splits)
  
  res <- augment(mod, newdata = holdout) %>%
    mutate(.resid = Survived -.fitted)
  res
}

#use map
loocv_data$results <- map(loocv_data$splits, holdout_results)
loocv_data$mse <- map_dbl(loocv_data$results, ~mean(.$.resid^2))
loocv_data

#overall MSE
loocv_data %>%
  summarize(mse_fare = mean(mse))
```
The mean squared error for survival by fare is 0.222
```{r}
#survive_class

#begin cross validation
loocv_data <- loo_cv(titanic_train)
loocv_data
#

holdout_results <- function(splits){

  mod <- glm(Survived ~ Pclass, data = analysis(splits)
             )  
  holdout <- assessment(splits)
  
  res <- augment(mod, newdata = holdout) %>%
    mutate(.resid = Survived -.fitted)
  res
}

#use map
loocv_data$results <- map(loocv_data$splits, holdout_results)
loocv_data$mse <- map_dbl(loocv_data$results, ~mean(.$.resid^2))
loocv_data

#overall MSE
loocv_data %>%
  summarize(mse_class = mean(mse))
```
The mean squared error rate for survival by class is 0.210.
```{r}
#survive_sex

#begin cross validation
loocv_data <- loo_cv(titanic_train)

#

holdout_results <- function(splits){

  mod <- glm(Survived ~ Sex, data = analysis(splits)
             )  
  holdout <- assessment(splits)
  
  res <- augment(mod, newdata = holdout) %>%
    mutate(.resid = Survived -.fitted)
  res
}

#use map
loocv_data$results <- map(loocv_data$splits, holdout_results)
loocv_data$mse <- map_dbl(loocv_data$results, ~mean(.$.resid^2))
loocv_data

#overall MSE
loocv_data %>%
  summarize(mse_sex = mean(mse))
```
The mean squared error rate for survival by sex is 0.167
```{r}
#Now estimate three random forest models. Generate random forests with 500 trees apiece.
#convert qualitative to factors
titanic_tree_data <- titanic_train %>%
  mutate(Survived = if_else(Survived == 1, "Survived", "Died"),
         Survived = as.factor(Survived),
         Sex = as.factor(Sex))

#make data ready for rf
titanic_rf_data <- titanic_tree_data %>%
  select(Survived, Pclass, Sex, Age, SibSp, Parch, Fare, Embarked) %>%
  na.omit()
titanic_rf_data

#run rf for age + Pclass
age_class_rf <- train(Survived ~ Age + Pclass, data = titanic_rf_data,
                   method = "rf",
                   ntree = 500,
                   trControl = trainControl(method = "oob"))

age_class_rf

#run rf for sex + Pclass
sex_class_rf <- train(Survived ~ Sex + Pclass, data = titanic_rf_data,
                   method = "rf",
                   ntree = 500,
                   trControl = trainControl(method = "oob"))

sex_class_rf
#run rf for sex + Pclass
sex_class_age_rf <- train(Survived ~ Sex + Pclass + Age, data = titanic_rf_data,
                   method = "rf",
                   ntree = 500,
                   trControl = trainControl(method = "oob"))
```

```{r}
sex_class_age_rf
#Generate variable importance plots for each random forest model. Which variables seem the most important?
#age and class
randomForest::varImpPlot(age_class_rf$finalModel)
#sex and class
randomForest::varImpPlot(sex_class_rf$finalModel)
#sex, class, and age
randomForest::varImpPlot(sex_class_age_rf$finalModel)
```

```{r}
#Calculate the out-of-bag error rate for each random forest model. Which performs the best?
#age and class
age_class_rf$finalModel
print("OOB Estimate = 20.87%")
#sex and class
sex_class_rf$finalModel
print("OOB Estimate = 20.87%")
#sex, class, and age
sex_class_age_rf$finalModel
print("OOB Estimate = 18.35%")

```

